### ISSUE TITLE
Driver does not support Azure redirect connections and error message is misleading

### ISSUE THREAD

**Issue by beoberha** [denisenkom/go-mssqldb#482]
Per internal Microsoft email thread, I am opening this issue to track the fact that this client driver does not support redirected connections. Further, attempts at using a redirected connection fail with a misleading error "TLS Handshake failed: x509: certificate is valid for {TR addresses}, not {ServerName}.database.windows.net".

**Comment by v-kaywon** [comment]
I will have time to work on it after around 2 weeks. I can't promise when I can finish since I'm not yet that familiar with the driver and I also need a better understand of how the redirect mode works, but a rough time estimate would be around 2 months. @denisenkom @kardianos can one of you assign me to this issue?

**Comment by v-kaywon** [comment]
Related issues #288 #282

**Comment by v-kaywon** [comment]
@beoberha we believe the issue should be fixed in the latest version of the driver. Can you try it out?

**Comment by beoberha** [comment]
Hi @v-kaywon - I am an engineer on Azure SQL DB and only created this issue because we had a customer requesting it. I see you have been in contact with @techjacker in the other thread. I believe he is the that reported this bug to us.

**Comment by techjacker** [comment]
@v-kaywon I tried https://github.com/denisenkom/go-mssqldb/pull/488 but it did not fix the issue for me. Have you pushed a fix in either of the subsequent 2 commits to master? I can't see that either of them would address this.

**Comment by v-kaywon** [comment]
@techjacker I'm having trouble reproducing the issue after #488 . Can you try my suggestion in adding these two lines
```
log.Println("routedServer:", sess.routedServer)
log.Println("hostInCertificate:", p.hostInCertificate)
```
after https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L1371 in the code so I can see if `hostInCertificate` is changed correctly?

**Comment by shueybubbles** [comment]
@kardianos I can reproduce this with a redirect-based azure server. The repro requires creation of multiple connections in the pool.

The initial connection works; mssql calls tls.Handshake twice, once with the foo.database.windows.net name then again with the redirected name.

When the second connection is created, it only calls tls.Handshake once, passing the redirected name.

```go

package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"

	mssql "github.com/denisenkom/go-mssqldb"
)


func main() {
	ctx := context.Background()
	connStr := "<your server/db/password>;Encrypt=True;TrustServerCertificate=False"

	conn, _ := mssql.NewConnector(connStr)
	db := sql.OpenDB(conn)
	db.SetMaxOpenConns(0)
	db.SetMaxIdleConns(10)
	defer db.Close()
	fmt.Println("Pinging")
	if err := db.PingContext(ctx); err != nil {
		log.Panic(err)
	}
	fmt.Println("select 100")
	r, err := db.QueryContext(ctx, "select 100")
	if err != nil {
		log.Panic(err)
	}
	//r.Close()

	fmt.Println("Select 200")
	if r, err = db.QueryContext(ctx, "select 200"); err != nil {
		log.Panic(err)
	}
	r.Close()
	fmt.Println("No errors!")
	os.Exit(0)
}

```

If you uncomment the first r.Close(), it works because only 1 connection is used.
